version: '3.8'

services:
  # API Cámara 1
  api-cam1:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./data/videos:/app/videos
      - ./data/frames:/app/frames_analizados
      - ./models:/app/models
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/0
      - CAMERA_ID=cam1
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network

  # Jupyter para cámara 1
  jupyter-cam1:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8881:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./videos:/app/videos
      - ./frames_analizados:/app/frames_analizados
    environment:
      - API_URL=http://api-cam1:8000
    networks:
      - app-network

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  # MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: